 # LU Decomposition
*Author : Satrya Budi Pratama*

Define : y = **A**x

using this method we can achive the **LU** given **A**

# Pseudocode
1. Generated **A** squared matrix using random value > 1  given the ordo(n)
2. Copy **A** to **U**
4. Create the **L** as Identity Matrix
3. Iterate over cols and iterate over cols but skip first row
    - calculate divider/factorize by divide current element with top element on same cols 
    - calculate gaussian elimination by **current rows** of U - (divider) * **first rows** of U, replace the result as new rows of **U**
    - put divider on that  **L** on the index rows,cols
6. Now we get **U** and **L**, check **L** dot **U** is same as **A**

Notes : 
sometimes this method doesn't have solution on LU Decomposition because the random of **A**, we need to check if **A** can be solved or unsolved first, and throw an error if it unsolved.

In [203]:
import numpy as np
np.set_printoptions(precision=3) # print 3 decimal

In [204]:
ordo = 5 # this mean A_5x5, we can change this 

In [205]:
# numpy.random.randint(min_val,max_val,(<num_rows>,<num_cols>))
A = np.random.randint(1,100,(ordo,ordo)).astype("float")
#A = np.array([[1 , -2],[3,2]])
A

array([[87., 51., 42., 53., 55.],
       [66.,  7.,  5.,  3., 18.],
       [12., 40., 21., 68., 18.],
       [ 9., 87., 86., 51.,  5.],
       [ 9., 44., 79., 84., 72.]])

In [208]:
rows, cols = np.shape(A) # get num of rows and col
# iterate over the columns idx 0..col-1
U = np.copy(A)
L = np.identity(rows) # create identiy matrix for L
# iterate over the rows and cols

# loop over the cols, skip last cols
for i in range(0,cols-1):
    print('\n')
    print('Step {}'.format(i+1))
    print('-----------------------')
    # loop over the rows, skip first row 
    for j in range(i+1,rows):
        factorize = U[j][i]/U[i][i] # current element divide by upper element on same cols
        print('[cols {0}] current/upper : {1:.2f}/{2:.2f} = {3:.2f}'.format(i,U[j][i],U[i][i],factorize))
        print('[rows {0} : {1}]'.format(i,U[i]))
        U[j] = U[j] - factorize * U[i] # do gaussian elimination
        print('[rows {0} : {1}]'.format(j,U[j]))
        
        L[j][i] = factorize # set the factorize to L
    
    print('-----------------------')
    # show the step        
    print('A{} : \n {}'.format(i,U))
    print('L{} : \n {}'.format(i,L))



Step 1
-----------------------
[cols 0] current/upper : 66.00/87.00 = 0.76
[rows 0 : [87. 51. 42. 53. 55.]]
[rows 1 : [  0.    -31.69  -26.862 -37.207 -23.724]]
[cols 0] current/upper : 12.00/87.00 = 0.14
[rows 0 : [87. 51. 42. 53. 55.]]
[rows 2 : [ 0.    32.966 15.207 60.69  10.414]]
[cols 0] current/upper : 9.00/87.00 = 0.10
[rows 0 : [87. 51. 42. 53. 55.]]
[rows 3 : [ 0.    81.724 81.655 45.517 -0.69 ]]
[cols 0] current/upper : 9.00/87.00 = 0.10
[rows 0 : [87. 51. 42. 53. 55.]]
[rows 4 : [ 0.    38.724 74.655 78.517 66.31 ]]
-----------------------
A0 : 
 [[ 87.     51.     42.     53.     55.   ]
 [  0.    -31.69  -26.862 -37.207 -23.724]
 [  0.     32.966  15.207  60.69   10.414]
 [  0.     81.724  81.655  45.517  -0.69 ]
 [  0.     38.724  74.655  78.517  66.31 ]]
L0 : 
 [[1.    0.    0.    0.    0.   ]
 [0.759 1.    0.    0.    0.   ]
 [0.138 0.    1.    0.    0.   ]
 [0.103 0.    0.    1.    0.   ]
 [0.103 0.    0.    0.    1.   ]]


Step 2
-----------------------
[cols 1] cu

In [210]:
print('{}'.format(L))

[[ 1.     0.     0.     0.     0.   ]
 [ 0.759  1.     0.     0.     0.   ]
 [ 0.138 -1.04   1.     0.     0.   ]
 [ 0.103 -2.579 -0.972  1.     0.   ]
 [ 0.103 -1.222 -3.284 -3.621  1.   ]]


In [209]:
print('{}'.format(U))

[[  87.      51.      42.      53.      55.   ]
 [   0.     -31.69   -26.862  -37.207  -23.724]
 [   0.       0.     -12.737   21.985  -14.266]
 [   0.       0.       0.     -29.065  -75.739]
 [   0.       0.       0.       0.    -283.81 ]]


# Testing

We can test, with L.U :

1. **A = L U**
2. y = **A**x
3. y = **L U** x
    to solve x, first we search b , using this formula two back-substitution :
    - y = U x
    - b = L y

    
4. **y = inverse(A) x**


## 1. Prove  A = LU

In [211]:
# first testing A = LU
A_lu = np.round(np.dot(L,U)) # ceil up the element of matrix;
A_lu

array([[87., 51., 42., 53., 55.],
       [66.,  7.,  5.,  3., 18.],
       [12., 40., 21., 68., 18.],
       [ 9., 87., 86., 51.,  5.],
       [ 9., 44., 79., 84., 72.]])

In [212]:
A

array([[87., 51., 42., 53., 55.],
       [66.,  7.,  5.,  3., 18.],
       [12., 40., 21., 68., 18.],
       [ 9., 87., 86., 51.,  5.],
       [ 9., 44., 79., 84., 72.]])

Compare **A** result using LU Decomposition with the **A** original one

In [213]:
A_lu == A # all true means proved A = LU

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 2. Prove  y = Ax

In [214]:
# generate random y
y = np.random.randint(1,100,(1,ordo)).astype("float") # generate random y
y = y[0]
y

array([90., 34., 99., 29., 70.])

In [215]:
# two back-substitution
def calculateX(U, Y):
    X = np.zeros(len(Y))
    for i in reversed(range(len(U))):
        X[i] = (Y[i] - sum(U[i][i+1:] * X[i+1:])) / U[i][i]
    return X

def calculateLY(L, B):
    Y = np.zeros(len(B))
    for i in range(len(L)):
        Y[i] = B[i] - sum(L[i] * Y)
    return Y

In [216]:
b = calculateLY(L, y) # calculate b using Ly
b

array([ 90.   , -34.276,  50.93 , -19.196, 116.555])

We can ge x using two-back substitution

In [217]:
x = calculateX(U,b) # calculate X using Ub
x

array([ 0.609, -0.175, -0.551,  1.731, -0.411])

In [218]:
# prove y = Ax
y_rest = A.dot(x)
y_rest

array([90., 34., 99., 29., 70.])

In [219]:
y

array([90., 34., 99., 29., 70.])

Compare y result using two back subtitution with the original one

In [220]:
np.round(y_rest) == np.round(y) # all true means proved y = Ax

array([ True,  True,  True,  True,  True])

## 3. Prove y = LUx

In [221]:
y_rest_LU = L.dot(U).dot(x)

In [222]:
y_rest_LU

array([90., 34., 99., 29., 70.])

In [223]:
y

array([90., 34., 99., 29., 70.])

Compare y result with the original one

In [224]:
np.round(y_rest_LU) == np.round(y) # all true means proved y = LUx

array([ True,  True,  True,  True,  True])

## 4. Prove x = inverse(A) * y

In [225]:
# using inverse
A_inv = np.linalg.inv(A)
A_inv

array([[-0.016,  0.034,  0.007,  0.003,  0.002],
       [ 0.062, -0.076, -0.015,  0.   , -0.025],
       [-0.044,  0.054, -0.002,  0.012,  0.02 ],
       [-0.034,  0.038,  0.029, -0.001,  0.009],
       [ 0.052, -0.062, -0.024, -0.013, -0.004]])

get x using inverse dot product y

In [226]:
# prove x = A-1 * y
x_res = A_inv.dot(y)

In [227]:
x_res

array([ 0.609, -0.175, -0.551,  1.731, -0.411])

In [228]:
x

array([ 0.609, -0.175, -0.551,  1.731, -0.411])

Compare x_result using inverse with x original from two-back subtitution

In [229]:
np.round(x_res) == np.round(x) # all true means proved x = A-1 * y

array([ True,  True,  True,  True,  True])