# LU Decomposition

Given the system:

```
3x0 + 2x1 + 4x2 = 1
 x0 +  x1 + 2x2 = 2
4x0 + 3x1 + 2x2 = 3
```

Calculate the X = [x0, x1, x2]

In [3]:
import numpy as np

In [21]:
A = np.array([
    [3., 2., 4.,6.],
    [1., 1., 2.,7.],
    [4., 3., 2.,8.],
    [5.,5.,6.,7.]
])

B = np.array([1., 2., 3., 4.])
B

array([1., 2., 3., 4.])

In [5]:
def luDecompose(A):
    U = A.copy()
    L = np.eye(len(A))
    P = np.arange(0, len(A))
    
    for i in range(0, len(U)-1):
        for j in range(i+1, len(U)):
            lower = U[j][i]/U[i][i]
            print('----------------')
            print('U[j][i]:{}'.format(U[j][i]) )
            print('U[i][i]:{}'.format(U[i][i]) )
            print('----------------')
            U[j] = U[j] - lower * U[i]
            print('----------------')
            print('cols : {} rows : {} \n U[j] : {}'.format(i,j,U[j]))
            print('cols : {} rows : {} \n U[i] : {}'.format(i,j,U[i]))
            print('----------------')
            L[P[j]][i] = lower
            print('----------------')
            print(P[j])
            print('--------------------')
            print('cols : {} rows : {} \n U :{}'.format(i,j,U))
            print('cols : {} rows : {} \n L :{}'.format(i,j,L))
            print('--------------------')
    return L, U
    
L, U = luDecompose(A)

print("L =", np.matrix.round(L, decimals=10))
print("")
print("U =", np.matrix.round(U, decimals=10))

----------------
U[j][i]:1.0
U[i][i]:3.0
----------------
----------------
cols : 0 rows : 1 
 U[j] : [0.         0.33333333 0.66666667 5.        ]
cols : 0 rows : 1 
 U[i] : [3. 2. 4. 6.]
----------------
----------------
1
--------------------
cols : 0 rows : 1 
 U :[[3.         2.         4.         6.        ]
 [0.         0.33333333 0.66666667 5.        ]
 [4.         3.         2.         8.        ]
 [5.         5.         6.         7.        ]]
cols : 0 rows : 1 
 L :[[1.         0.         0.         0.        ]
 [0.33333333 1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         0.         1.        ]]
--------------------
----------------
U[j][i]:4.0
U[i][i]:3.0
----------------
----------------
cols : 0 rows : 2 
 U[j] : [ 0.          0.33333333 -3.33333333  0.        ]
cols : 0 rows : 2 
 U[i] : [3. 2. 4. 6.]
----------------
----------------
2
--------------------
cols : 0 rows : 2 
 U :[[ 3.          2.          4.       

In [6]:
----

With the L.U:
    
```
    A x = y
    L U x = y
      ---
      
    U X = Y
    L y = b
    
    
```

----

First calculate Y:

SyntaxError: invalid syntax (<ipython-input-6-f2ab74fca74e>, line 1)

In [7]:
np.dot(L,U)

array([[3., 2., 4., 6.],
       [1., 1., 2., 7.],
       [4., 3., 2., 8.],
       [5., 5., 6., 7.]])

In [8]:
def calculateY(L, B):
    Y = np.zeros(len(B))
    for i in range(len(L)):
        Y[i] = B[i] - sum(L[i] * Y)
    return Y
    
Y = calculateY(L, B)

print("Y =", np.matrix.round(Y, decimals=10))

Y = [ 1.          1.66666667 -0.         -6.        ]


In [9]:
L*B

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.33333333,  2.        ,  0.        ,  0.        ],
       [ 1.33333333,  2.        ,  3.        ,  0.        ],
       [ 1.66666667, 10.        ,  3.        ,  4.        ]])

----

Then calculate X:

In [10]:
def calculateX(U, Y):
    X = np.zeros(len(Y))
    for i in reversed(range(len(U))):
        X[i] = (Y[i] - sum(U[i][i+1:] * X[i+1:])) / U[i][i]
    return X

X = calculateX(U, Y)

print("X =", np.matrix.round(X, decimals=10))

X = [-0.91304348  1.73913043 -0.32608696  0.26086957]


In [11]:
def test_system(A, X, B):
    Br = A.dot(X)
    assert len(Br) == len(B)
    for i in range(len(B)):
        actual = np.round(B[i], decimals=10)
        result = np.round(Br[i], decimals=10)
        msg = "value %.2f != %.2f at index %d" % (actual, result, i)
        assert actual == result, msg

In [12]:
test_system(A, X, B)

----

Validando com matrizes aleatorias

In [19]:
def calc_and_test(A, B):
    L, U = luDecompose(A)
    Y = calculateY(L, B)
    print('Y')
    print(Y)
    X = calculateX(U, Y)
    print('X')
    print(X)
    test_system(A=A, X=X, B=B)
    print("system ok")

In [20]:
A1 = np.array([
    [3.0, 2.0, 0.3, 0.],
    [1.5, 0.1, 0.4, 2.],
    [2.0, 0.0, 1.0, 0.],
    [1.1, 1.1, 2.0, 4.]
])
B1 = np.array([2.0, 3.0, 1.1, 4.0])

calc_and_test(A1, B1)

----------------
U[j][i]:1.5
U[i][i]:3.0
----------------
----------------
cols : 0 rows : 1 
 U[j] : [ 0.   -0.9   0.25  2.  ]
cols : 0 rows : 1 
 U[i] : [3.  2.  0.3 0. ]
----------------
----------------
1
--------------------
cols : 0 rows : 1 
 U :[[ 3.    2.    0.3   0.  ]
 [ 0.   -0.9   0.25  2.  ]
 [ 2.    0.    1.    0.  ]
 [ 1.1   1.1   2.    4.  ]]
cols : 0 rows : 1 
 L :[[1.  0.  0.  0. ]
 [0.5 1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]
--------------------
----------------
U[j][i]:2.0
U[i][i]:3.0
----------------
----------------
cols : 0 rows : 2 
 U[j] : [ 0.         -1.33333333  0.8         0.        ]
cols : 0 rows : 2 
 U[i] : [3.  2.  0.3 0. ]
----------------
----------------
2
--------------------
cols : 0 rows : 2 
 U :[[ 3.          2.          0.3         0.        ]
 [ 0.         -0.9         0.25        2.        ]
 [ 0.         -1.33333333  0.8         0.        ]
 [ 1.1         1.1         2.          4.        ]]
cols : 0 rows : 2 
 L :[[1.        

In [15]:
A2 = np.array([
    [1.0, 3.0, 5.0],
    [2.0, 4.0, 7.0],
    [1.0, 1.0, 0.0]
])
B2 = np.array([0.0, 1.0, -2.0])

calc_and_test(A2, B2)

----------------
U[j][i]:2.0
U[i][i]:1.0
----------------
----------------
cols : 0 rows : 1 
 U[j] : [ 0. -2. -3.]
cols : 0 rows : 1 
 U[i] : [1. 3. 5.]
----------------
----------------
1
--------------------
cols : 0 rows : 1 
 U :[[ 1.  3.  5.]
 [ 0. -2. -3.]
 [ 1.  1.  0.]]
cols : 0 rows : 1 
 L :[[1. 0. 0.]
 [2. 1. 0.]
 [0. 0. 1.]]
--------------------
----------------
U[j][i]:1.0
U[i][i]:1.0
----------------
----------------
cols : 0 rows : 2 
 U[j] : [ 0. -2. -5.]
cols : 0 rows : 2 
 U[i] : [1. 3. 5.]
----------------
----------------
2
--------------------
cols : 0 rows : 2 
 U :[[ 1.  3.  5.]
 [ 0. -2. -3.]
 [ 0. -2. -5.]]
cols : 0 rows : 2 
 L :[[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]
--------------------
----------------
U[j][i]:-2.0
U[i][i]:-2.0
----------------
----------------
cols : 1 rows : 2 
 U[j] : [ 0.  0. -2.]
cols : 1 rows : 2 
 U[i] : [ 0. -2. -3.]
----------------
----------------
2
--------------------
cols : 1 rows : 2 
 U :[[ 1.  3.  5.]
 [ 0. -2. -3.]
 [ 0.  0.

In [16]:
A3 = np.array([
    [5.0, 3.0, 1.0],
    [0.0, 1.0, 1.0],
    [-1.0, -1.0, 1.0]
])
B3 = np.array([-6.0, -1.0, 7.0])

calc_and_test(A3, B3)

----------------
U[j][i]:0.0
U[i][i]:5.0
----------------
----------------
cols : 0 rows : 1 
 U[j] : [0. 1. 1.]
cols : 0 rows : 1 
 U[i] : [5. 3. 1.]
----------------
----------------
1
--------------------
cols : 0 rows : 1 
 U :[[ 5.  3.  1.]
 [ 0.  1.  1.]
 [-1. -1.  1.]]
cols : 0 rows : 1 
 L :[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
----------------
U[j][i]:-1.0
U[i][i]:5.0
----------------
----------------
cols : 0 rows : 2 
 U[j] : [ 0.  -0.4  1.2]
cols : 0 rows : 2 
 U[i] : [5. 3. 1.]
----------------
----------------
2
--------------------
cols : 0 rows : 2 
 U :[[ 5.   3.   1. ]
 [ 0.   1.   1. ]
 [ 0.  -0.4  1.2]]
cols : 0 rows : 2 
 L :[[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [-0.2  0.   1. ]]
--------------------
----------------
U[j][i]:-0.3999999999999999
U[i][i]:1.0
----------------
----------------
cols : 1 rows : 2 
 U[j] : [0.  0.  1.6]
cols : 1 rows : 2 
 U[i] : [0. 1. 1.]
----------------
----------------
2
--------------------
cols : 1 rows : 2 
 U :

In [17]:
A4 = np.array([
    [ 2., 1., 1., 0. ],
    [ 0., 1., 1., 1. ],
    [ 0., 0., 2., 2. ],
    [ 0., 0., 0., 2. ],
])

B4 = np.array([1., 0., 0., 2.])

calc_and_test(A4, B4)

----------------
U[j][i]:0.0
U[i][i]:2.0
----------------
----------------
cols : 0 rows : 1 
 U[j] : [0. 1. 1. 1.]
cols : 0 rows : 1 
 U[i] : [2. 1. 1. 0.]
----------------
----------------
1
--------------------
cols : 0 rows : 1 
 U :[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]
cols : 0 rows : 1 
 L :[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------
----------------
U[j][i]:0.0
U[i][i]:2.0
----------------
----------------
cols : 0 rows : 2 
 U[j] : [0. 0. 2. 2.]
cols : 0 rows : 2 
 U[i] : [2. 1. 1. 0.]
----------------
----------------
2
--------------------
cols : 0 rows : 2 
 U :[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]
cols : 0 rows : 2 
 L :[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------
----------------
U[j][i]:0.0
U[i][i]:2.0
----------------
----------------
cols : 0 rows : 3 
 U[j] : [0. 0. 0. 2.]
cols : 0 rows : 3 
 U[i] : [2. 1. 1. 0.]
----------------
----------------
3
-

In [18]:
A5 = np.array([
    [ 2., 1., 1., 0. ],
    [ 4., 3., 3., 1. ],
    [ 8., 7., 9., 5. ],
    [ 6., 7., 9., 8. ]
])

B5 = np.array( [ 1., 2., 4., 5. ])

calc_and_test(A5, B5)

----------------
U[j][i]:4.0
U[i][i]:2.0
----------------
----------------
cols : 0 rows : 1 
 U[j] : [0. 1. 1. 1.]
cols : 0 rows : 1 
 U[i] : [2. 1. 1. 0.]
----------------
----------------
1
--------------------
cols : 0 rows : 1 
 U :[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [8. 7. 9. 5.]
 [6. 7. 9. 8.]]
cols : 0 rows : 1 
 L :[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------
----------------
U[j][i]:8.0
U[i][i]:2.0
----------------
----------------
cols : 0 rows : 2 
 U[j] : [0. 3. 5. 5.]
cols : 0 rows : 2 
 U[i] : [2. 1. 1. 0.]
----------------
----------------
2
--------------------
cols : 0 rows : 2 
 U :[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 3. 5. 5.]
 [6. 7. 9. 8.]]
cols : 0 rows : 2 
 L :[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------
----------------
U[j][i]:6.0
U[i][i]:2.0
----------------
----------------
cols : 0 rows : 3 
 U[j] : [0. 4. 6. 8.]
cols : 0 rows : 3 
 U[i] : [2. 1. 1. 0.]
----------------
----------------
3
-