# Least Squares Approximations
*Author : Satrya Budi Pratama*


It often happens that $\mathbf{A}x=b$ has no solution. 
Several reason are : 


 - The usual reason is: too many equations.
 - The matrix has more rows than columns. 
 - There are more equations than unknowns (m is greater than n). The n columns span a small part of m-dimensional space. 
 - Unless all measurements are perfect, b is outside that column space. 
 
So elimination reaches an impossible equation and stops. But we can’t stop just because measurements include noise.

When $\mathbf{A}x=b$ has no solution, multiply by $\mathbf{A}^\intercal$ and solve $\mathbf{A}^\intercal \mathbf{A}\hat{x} = \mathbf{A}^\intercal b$. So to get the approximations solution $\hat{x}$, we can get $\hat{x}=(\mathbf{A}^\intercal A)^{-1}\mathbf{A}^\intercal b$.

They are connected by the projection $p=A\hat{x}$.

For example we use :
$Ax = b$

$\begin{bmatrix} 1 & 1\\
2 & 1  \\
3 & 1\end{bmatrix}\begin{bmatrix}x_{1}\\x_{2} \end{bmatrix} = \begin{bmatrix}1\\2\\2\end{bmatrix}$

In this notebook we solve x using least square, get the projection, and the error

In [73]:
import numpy as np
import math
A = np.array([[1. , 1.],
             [2., 1.],
             [3., 1.]])
b = np.array([1., 2., 2.])

In [74]:
A

array([[1., 1.],
       [2., 1.],
       [3., 1.]])

In [75]:
b

array([1., 2., 2.])

## Least Squares Solution  
$\hat{x}=(\mathbf{A}^\intercal A)^{-1}\mathbf{A}^\intercal b$

In [76]:
x = np.linalg.inv(A.transpose().dot(A)).dot(A.transpose().dot(b))
x

array([0.5       , 0.66666667])

## The Projection matrix ($p$)

$p=A\hat{x}$

In [77]:
p = A.dot(x)
p

array([1.16666667, 1.66666667, 2.16666667])

## The error
$e = b - A\hat{x}$ or  $e = b - p$

In [78]:
e = b - A.dot(x)
e

array([-0.16666667,  0.33333333, -0.16666667])

In [79]:
e = b - p
e

array([-0.16666667,  0.33333333, -0.16666667])

In [80]:
# MAE
mae = np.average(abs(e))
mae

0.22222222222222263

In [81]:
# MSE
power = np.power(e,2)
mse = np.average(power)
mse

0.05555555555555556

In [82]:
# RMSE
rmse = math.sqrt(mse)
rmse

0.23570226039551584

When e is zero,
$\hat{x}$ is an exact solution to $\mathbf{A}x=b$

# References
- http://math.mit.edu/~gs/linearalgebra/ila0403.pdf
- https://medium.com/analytics-vidhya/forecast-kpi-rmse-mae-mape-bias-cdc5703d242d