# QR Decomposition
*Author : Satrya Budi Pratama*

How to make $\mathbf{A}$ which is not orthogonal to orthogonal using Gram-Schmidt to get $\mathbf{Q}$. Using that method we can also calculate the $\mathbf{R}$ for QR Decomposition.

$A = QR$

where $Q$ is $(n×n)$ orthogonal $(Q^TQ = I)$ and $R$ is $(n×n)$ upper triangular.

For example given  $A = \begin{bmatrix} 1 & 2 & 4\\
0 & 0 & 5  \\
0 & 3 & 6\end{bmatrix}$, where $a_1 =\begin{bmatrix} 1\\0\\0 \end{bmatrix},a_2 =\begin{bmatrix} 2\\0\\3 \end{bmatrix},a_3 =\begin{bmatrix} 4\\5\\6 \end{bmatrix}$ our goals it to calculate $q_1 , q_2$ and $q_3$

using this formula $q_n = \frac{w_n}{|| w_n ||}$ where $w_n = a_n - \sum^{n-1}_{i=1} (a_n^\intercal q_i)q_i$ and $|| w_n || = \sqrt{w_n^\intercal w_n}$


The pseudocode are :


1. Generate $A$
2. Call QR Decomposition
    - generate zeros matrix as Q, and R
    - iterate over column 
        - for first iterate update first Q = current cols / euclidean of first cols and update R for its norm
        - and next iterate we do iteration as many of q then calculate w using the formula, update Q and R.
    - return Q and R
3. Prove $A = QR$



In [5]:
import numpy as np
A = np.array([[1. , 2. , 4.],
            [0., 0., 5.],
            [0., 3., 6.]])
A

array([[1., 2., 4.],
       [0., 0., 5.],
       [0., 3., 6.]])

In [6]:
def QRDecomposition(A):
    rows,cols = A.shape
    Q = np.zeros((rows,cols))
    R = np.zeros((rows,cols))
    
    # iterate over cols
    for i in range(cols):
        print('\n --- Step {} : ---- \n'.format(i+1))
        if i == 0:
            # first cols
            w_norm =  np.sqrt(np.transpose(A[:,i]).dot(A[:,i])) # norm euclidean of first cols
            Q[:,i] = A[:,i] / w_norm # calculate Q
            R[i,i] = w_norm # put norm to R
        else:
            idx_rows = 0
            print('-- inner loop --')
            w = np.zeros(rows) 
            #print(w)
            for j in range(i):
                # inner loop for calculate sigma
                w_product = np.transpose(A[:,i]).dot(Q[:,idx_rows]) # calculate dot product An^T with Qn.
                R[idx_rows,i] = w_product # put w_product to R
                w_sigma = w_product * Q[:,idx_rows] # dot q, (An^T*Qi)Qi
                w =  w + w_sigma # summation the result
                idx_rows += 1
                print('w_product : {} \t w_sigma: {} \n w : {} '.format(w_product,w_sigma, w))
            
            w = A[:,i].transpose() - w # An - summation 
            w = w.transpose() # change the shape
            w_norm = np.sqrt(np.transpose(w).dot(w)) # calculate norm of w
            R[i,i] = w_norm # put norm to R
            Q[:,i] = w / w_norm # calculate Q 
            print('-- outer -- ')
            print('w : {} , w_norm : {}'.format(w,w_norm))
            
        print('-- Result --')
        print(' Q: {} \n\n R: {}'.format(Q, R))
    
    return Q, R
        
Q,R = QRDecomposition(A)


 --- Step 1 : ---- 

-- Result --
 Q: [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

 R: [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 --- Step 2 : ---- 

-- inner loop --
w_product : 2.0 	 w_sigma: [2. 0. 0.] 
 w : [2. 0. 0.] 
-- outer -- 
w : [0. 0. 3.] , w_norm : 3.0
-- Result --
 Q: [[1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 0.]] 

 R: [[1. 2. 0.]
 [0. 3. 0.]
 [0. 0. 0.]]

 --- Step 3 : ---- 

-- inner loop --
w_product : 4.0 	 w_sigma: [4. 0. 0.] 
 w : [4. 0. 0.] 
w_product : 6.0 	 w_sigma: [0. 0. 6.] 
 w : [4. 0. 6.] 
-- outer -- 
w : [0. 5. 0.] , w_norm : 5.0
-- Result --
 Q: [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] 

 R: [[1. 2. 4.]
 [0. 3. 6.]
 [0. 0. 5.]]


Testing $A = Q*R$

In [7]:
# prove
# A = Q*R
A_qr = Q.dot(R)
A_qr

array([[1., 2., 4.],
       [0., 0., 5.],
       [0., 3., 6.]])

In [8]:
A_qr == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
# try with A random
n = 5
A = np.random.rand(n,n)
A

array([[0.54366257, 0.45876114, 0.08862018, 0.36770131, 0.57946619],
       [0.3153552 , 0.1685013 , 0.1054826 , 0.51139564, 0.26009534],
       [0.46142187, 0.88814777, 0.48847009, 0.27508568, 0.82076906],
       [0.58945593, 0.74701087, 0.95224502, 0.33371479, 0.65439308],
       [0.73422061, 0.22821327, 0.99034256, 0.9185952 , 0.05493094]])

In [16]:
Q, R = QRDecomposition(A)


 --- Step 1 : ---- 

-- Result --
 Q: [[0.44471971 0.         0.         0.         0.        ]
 [0.25796272 0.         0.         0.         0.        ]
 [0.37744625 0.         0.         0.         0.        ]
 [0.482179   0.         0.         0.         0.        ]
 [0.6005975  0.         0.         0.         0.        ]] 

 R: [[1.22248364 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]

 --- Step 2 : ---- 

-- inner loop --
w_product : 1.079972492259144 	 w_sigma: [0.48028506 0.27859264 0.40763157 0.52074005 0.64862878] 
 w : [0.48028506 0.27859264 0.40763157 0.52074005 0.64862878] 
-- outer -- 
w : [-0.02152391 -0.11009134  0.4805162   0.22627082 -0.42041551] , w_norm : 0.6866053311427806
-- Result --
 Q: [[ 0.44471971 -0.03134831  0.          0.     

In [17]:
A_qr = Q.dot(R)
A_qr

array([[0.54366257, 0.45876114, 0.08862018, 0.36770131, 0.57946619],
       [0.3153552 , 0.1685013 , 0.1054826 , 0.51139564, 0.26009534],
       [0.46142187, 0.88814777, 0.48847009, 0.27508568, 0.82076906],
       [0.58945593, 0.74701087, 0.95224502, 0.33371479, 0.65439308],
       [0.73422061, 0.22821327, 0.99034256, 0.9185952 , 0.05493094]])

In [18]:
np.round(A) == np.round(A_qr)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# References
http://ee263.stanford.edu/lectures/qr.pdf

http://people.inf.ethz.ch/gander/papers/qrneu.pdf