In [1]:
import numpy as np

def geser_kanan(matrix, matrix_row_len, matrix_col_len, i, geser_kanan_count):
    #print("i = {}, geser_kanan = {}\n".format(i, geser_kanan))
    #print("val={}\n".format(matrix[i][i+geser_kanan]))
    if (matrix[i][i+geser_kanan_count] == 0):
        #print("not run\n")
        print("matrix[i][i] == zero at i = {}".format(i))
        for l in range(1, matrix_row_len-i):
            #print("matrix[[{}, {}]] = matrix[[{}, {}]]".format(i,i+l,i+l,i))
            matrix[[i, i+l]] = matrix[[i+l, i]]
            #print("matrix sementara = \n{}\n".format(matrix))
            if (matrix[i][i] != 0):
                print("returning\n")
                return geser_kanan_count
                print("imp\n")
        print("all row at i = {} is zero\n".format(i))
        geser_kanan_count += 1
        if (i + geser_kanan_count == matrix_col_len):
            print("no more\n")
            return -1
        else:
            geser_kanan(matrix, matrix_row_len, matrix_col_len, i, geser_kanan_count)
    return geser_kanan_count

def gauss_elimination(matrix_a, matrix_row_len,  matrix_col_len):
    matrix = np.copy(matrix_a)
    for i in range(matrix_row_len-1):
        #print("i = {}\n".format(i))
        geser_kanan_count = 0
        if (matrix[i][i] == 0):
            geser_kanan_count = geser_kanan(matrix, matrix_row_len, matrix_col_len, i, geser_kanan_count)
            # print("matrix[i][i] == zero at i = {}".format(i))
            # for l in range(1, matrix_row_len-i):
            #     print("matrix[[{}, {}]] = matrix[[{}, {}]]".format(i,i+l,i+l,i))
            #     matrix[[i, i+l]] = matrix[[i+l, i]]
            #     print("matrix sementara = \n{}\n".format(matrix))
            #     if (matrix[i][i] != 0):
            #         break
            # print("all row at i = {} is zero\n".format(i))

        #if()
        print("geser_kanan after = {}\n".format(geser_kanan))
        if geser_kanan_count < 0:
            return matrix

        for j in range(i+1, matrix_row_len):
            #print("j = {}\n".format(j))
            if matrix[i][i+geser_kanan_count] == 0:
                print("shouldnt happen\n")
            else:
                pengali = matrix[j][i+geser_kanan_count]/matrix[i][i+geser_kanan_count]
            for k in range(matrix_col_len):
                #print("k = {}\n".format(k))
                matrix[j][k] = matrix[j][k]-pengali*matrix[i][k]
            #print("matrix sementara = \n{}\n".format(matrix))
    return matrix

def main():
    #create SQUARE MATRIX with size=MATRIX_SIZE and element values between 0 and MAX_INT
    matrix_a = np.array([[1, 2, 1, 1, 5], [-2, -4, 0, 4, -2], [1, 2, 2, 4, 9]])
    print(" A = \n{}\n".format(matrix_a))
    matrix_a_ge = gauss_elimination(matrix_a, np.size(matrix_a, 0), np.size(matrix_a, 1))
    print(" A after gauss elimination = \n{}\n".format(matrix_a_ge))
    matrix_at = np.transpose(matrix_a)
    print(" At = \n{}\n".format(matrix_at))
    matrix_at_ge = gauss_elimination(matrix_at, np.size(matrix_at, 0), np.size(matrix_at, 1))
    print(" At after gauss elimination = \n{}\n".format(matrix_at_ge))

if __name__ == "__main__":
    main()

 A = 
[[ 1  2  1  1  5]
 [-2 -4  0  4 -2]
 [ 1  2  2  4  9]]

geser_kanan after = <function geser_kanan at 0x7f9da8442b90>

matrix[i][i] == zero at i = 1
all row at i = 1 is zero

geser_kanan after = <function geser_kanan at 0x7f9da8442b90>

 A after gauss elimination = 
[[1 2 1 1 5]
 [0 0 1 3 4]
 [0 0 0 0 0]]

 At = 
[[ 1 -2  1]
 [ 2 -4  2]
 [ 1  0  2]
 [ 1  4  4]
 [ 5 -2  9]]

geser_kanan after = <function geser_kanan at 0x7f9da8442b90>

matrix[i][i] == zero at i = 1
returning

geser_kanan after = <function geser_kanan at 0x7f9da8442b90>

matrix[i][i] == zero at i = 2
all row at i = 2 is zero

no more

geser_kanan after = <function geser_kanan at 0x7f9da8442b90>

 At after gauss elimination = 
[[ 1 -2  1]
 [ 0  2  1]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]

